version: "3.9"

networks:
  tracing:
    name: tracing

services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    user: "0"
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
      - ./.data:/etc/otelcol-contrib/.data
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./golang/logs:/var/log/myapp

  redis:
    image: redis:latest
    container_name: my-redis-container
    ports:
      - "6379:6379"
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local


