receivers:
  filelog:
    include:
      - /var/lib/docker/containers/*/*.log
      - /var/log/myapp/*.log
    start_at: end
    storage: file_storage

extensions:
  file_storage:
    directory: /etc/otelcol-contrib/.data/storage
    create_directory: true

exporters:
  file:
    path: /etc/otelcol-contrib/.data/output_logs.log

service:
  extensions: [file_storage]
  pipelines:
    logs:
      receivers: [filelog]
      processors: []
      exporters: [file]

# exporters:
#   otlp:
#     endpoint: otelcol:4317
#     sending_queue:
#       batch:

# extensions:
#   health_check:
#     endpoint: 0.0.0.0:13133
#   pprof:
#     endpoint: 0.0.0.0:1777
#   zpages:
#     endpoint: 0.0.0.0:55679

# service:
#   extensions: [health_check, pprof, zpages]
#   pipelines:
#     traces:
#       receivers: [otlp]
#       exporters: [otlp]
#     metrics:
#       receivers: [otlp]
#       exporters: [otlp]
#     logs:
#       receivers: [otlp]
#       exporters: [otlp]
