// Code generated by MockGen. DO NOT EDIT.
// Source: cache/cacheService.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCacheService is a mock of CacheService interface.
type MockCacheService struct {
	ctrl     *gomock.Controller
	recorder *MockCacheServiceMockRecorder
}

// MockCacheServiceMockRecorder is the mock recorder for MockCacheService.
type MockCacheServiceMockRecorder struct {
	mock *MockCacheService
}

// NewMockCacheService creates a new mock instance.
func NewMockCacheService(ctrl *gomock.Controller) *MockCacheService {
	mock := &MockCacheService{ctrl: ctrl}
	mock.recorder = &MockCacheServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheService) EXPECT() *MockCacheServiceMockRecorder {
	return m.recorder
}

// CreateNewSet mocks base method.
func (m *MockCacheService) CreateNewSet(imageNames []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewSet", imageNames)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNewSet indicates an expected call of CreateNewSet.
func (mr *MockCacheServiceMockRecorder) CreateNewSet(imageNames interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewSet", reflect.TypeOf((*MockCacheService)(nil).CreateNewSet), imageNames)
}

// GetImageName mocks base method.
func (m *MockCacheService) GetImageName() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImageName")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImageName indicates an expected call of GetImageName.
func (mr *MockCacheServiceMockRecorder) GetImageName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImageName", reflect.TypeOf((*MockCacheService)(nil).GetImageName))
}

// StoreImageName mocks base method.
func (m *MockCacheService) StoreImageName(imageName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreImageName", imageName)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreImageName indicates an expected call of StoreImageName.
func (mr *MockCacheServiceMockRecorder) StoreImageName(imageName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreImageName", reflect.TypeOf((*MockCacheService)(nil).StoreImageName), imageName)
}
